-- ============================================================
--  The Archive — initial inventory
--
--  GENERATED FILE — do not edit by hand.
--  Regenerate with: node scripts/generate-seed.js
--
--  Run this once, after schema.sql (see SETUP.md). Re-running is
--  safe: existing rows are left untouched, so anything you have
--  since edited in the app will not be clobbered back to these
--  original values.
-- ============================================================

insert into public.items (id, name, brand, size, category, price, source, notes, photo) values
  ('seed_0', 'Fleece jacket', 'Patagonia', '-', 'Jackets', 'NZD $142.00', 'Depop', 'Grey. From @hiddenheatvault.', 'wardrobe-photos/patagonia-fleece-jacket-retro-x-cream-nobg.png'),
  ('seed_1', 'Tunic jumper', 'Free People', 'L', 'Knitwear', 'NZD $49.50', 'Depop', 'Black, small hole at neck. From @ameeliegg.', 'wardrobe-photos/free-people-tunic-jumper-black-nobg.png'),
  ('seed_2', 'Fleece jacket', 'Billabong', 'L', 'Jackets', 'NZD $47.00', 'Depop', 'Brown/cream floral. From @userselling2359.', 'wardrobe-photos/billabong-fleece-jacket-brown-cream-floral-nobg.png'),
  ('seed_3', 'Corduroy jacket', 'Billabong', '-', 'Jackets', 'NZD $90.00', 'Depop', 'Vintage. From @pentupthrift.', 'wardrobe-photos/billabong-corduroy-jacket-v2-nobg.png'),
  ('seed_4', 'Fleece jacket', 'Quiksilver', 'XL', 'Jackets', 'NZD $68.00', 'Depop', 'Cream. From @finnrobins.', 'wardrobe-photos/quiksilver-van-life-sherpa-fleece-nobg.png'),
  ('seed_5', 'Jacket', 'Carhartt', 'XL', 'Jackets', 'NZD $155.00', 'Depop', 'Awaiting shipping. From @mangoe2.', 'wardrobe-photos/carhartt-jacket-detroit-nobg.png'),
  ('seed_6', 'Jacket', 'Carhartt', '-', 'Jackets', 'NZD $137.00', 'Depop', 'Tan, relaxed fit. From @klebh.', 'wardrobe-photos/carhartt-jacket-tan-chore-coat-nobg.png'),
  ('seed_7', 'Indi Coat', 'Tree of Life', '10, 12', 'Jackets', 'NZD $70.00', 'Designer Wardrobe', 'Seller: Susan A. Payment Received.', 'wardrobe-photos/tree-of-life-indi-coat-flat-nobg.png'),
  ('seed_8', 'Waverly jacket', 'Assembly Label', '10, 12', 'Jackets', 'NZD $100.00', 'Designer Wardrobe', 'Seller: April W.', 'wardrobe-photos/assembly-label-waverly-jacket-sand-flat-nobg.png'),
  ('seed_9', '585 Rustic Brown boots', 'Blundstone', '7', 'Shoes', 'NZD $110.00', 'Designer Wardrobe', 'Seller: Caroline.', 'wardrobe-photos/blundstone-585-rustic-brown-boots-nobg.png'),
  ('seed_10', 'Black Refined Tall Rain Boots', 'Hunter Boots', '8', 'Shoes', 'NZD $170.00', 'Designer Wardrobe', 'Seller: Carmel R.', 'wardrobe-photos/hunter-boots-refined-tall-rain-boots-v2-nobg.png'),
  ('seed_11', 'Jeans low and straight', 'Abrand', '28', 'Jeans', 'NZD $25.00', 'Designer Wardrobe', 'Seller: Emma J.', 'wardrobe-photos/abrand-jeans-low-and-straight-v2-nobg.png'),
  ('seed_12', 'Cream Knit Pants', 'Zulu & Zephyr', '10', 'Pants', 'NZD $90.00', 'Designer Wardrobe', 'Seller: Melanie N.', 'wardrobe-photos/zulu-zephyr-cream-knit-pants-nobg.png'),
  ('seed_13', 'Waverly Jacket', 'Assembly Label', '14, 16, 12', 'Jackets', 'NZD $110.00', 'Designer Wardrobe', 'Seller: Jord O.', 'wardrobe-photos/assembly-label-waverly-jacket-dark-choc-flat-nobg.png'),
  ('seed_14', 'Loose fit jeans', 'Assembly Label', '27', 'Jeans', 'NZD $100.00', 'Designer Wardrobe', 'Seller: Rachel Y.', 'wardrobe-photos/assembly-label-loose-fit-jeans-flat-nobg.png'),
  ('seed_15', 'Dolman jacket', 'Free People', '8', 'Jackets', 'NZD $195.00', 'Designer Wardrobe', 'Seller: Emma O.', 'wardrobe-photos/free-people-dolman-jacket-flat-nobg.png'),
  ('seed_16', 'Nikova knit', 'Bronze Snake Shop', '12', 'Knitwear', 'NZD $120.00', 'Designer Wardrobe', 'Seller: Stella M.', 'wardrobe-photos/bronze-snake-shop-nikova-knit-flat-nobg.png'),
  ('seed_17', 'Boyfriend Jean', 'Assembly Label', '30', 'Jeans', 'NZD $90.00', 'Designer Wardrobe', 'Seller: Ashleigh.', 'wardrobe-photos/assembly-label-boyfriend-jean-flat-nobg.png'),
  ('seed_18', 'Shirt/jacket', 'Marle', '12', 'Jackets', 'NZD $70.00', 'Designer Wardrobe', 'Seller: Clare H.', 'wardrobe-photos/marle-shirt-jacket-black-nobg.png'),
  ('seed_19', 'Denim Shirt', 'Marle', '12', 'Jackets', 'NZD $80.00', 'Designer Wardrobe', 'Seller: Claire H.', 'wardrobe-photos/marle-denim-shirt-light-blue-nobg.png'),
  ('seed_20', 'Beige Heels', 'Windsor Smith', '8', 'Shoes', 'NZD $40.70', 'Designer Wardrobe', 'Seller: Melody B.', null),
  ('seed_21', 'Sailor jeans - Lily blue', 'Rollas', '30', 'Jeans', 'NZD $40.00', 'Designer Wardrobe', 'Seller: Tracy H.', 'wardrobe-photos/rollas-sailor-jean-lily-blue-v2-nobg.png'),
  ('seed_22', 'Blue Striped Shirt', 'Assembly Label', '14', 'Shirts', 'NZD $40.00', 'Designer Wardrobe', 'Seller: Samantha.', 'wardrobe-photos/assembly-label-blue-striped-shirt-nobg.png'),
  ('seed_23', 'Black Linen Shirt', 'Assembly Label', '16', 'Shirts', 'NZD $40.00', 'Designer Wardrobe', 'Seller: Samantha.', 'wardrobe-photos/assembly-label-xander-linen-shirt-black-nobg.png'),
  ('seed_24', 'Santi Jumper', 'Marle', '12', 'Knitwear', 'NZD $125.00', 'Designer Wardrobe', 'Seller: Lorna F.', 'wardrobe-photos/marle-santi-jumper-flat-nobg.png'),
  ('seed_25', 'The Iconic Beach Shirt', 'Endless', '8', 'Shirts', 'NZD $26.00', 'Designer Wardrobe', 'Seller: Maggie H.', null),
  ('seed_26', 'Square Scarf', 'Unbranded', '8', 'Accessories', 'NZD $30.00', 'Designer Wardrobe', 'Seller: Riley N.', null),
  ('seed_27', 'Brown T-shirt (relaxed fit)', 'COS', 'M, L', 'Tops', 'NZD $30.50', 'Designer Wardrobe', 'Seller: Irina T.', 'wardrobe-photos/cos-relaxed-brown-tshirt-cutout.png'),
  ('seed_28', 'Eastcoast Flare', 'Rollas', '27', 'Pants', 'NZD $94.00', 'Designer Wardrobe', 'Seller: Laura J.', 'wardrobe-photos/rollas-eastcoast-flare-flat-nobg.png'),
  ('seed_29', 'Remi Top', 'With Jean', '8', 'Tops', 'NZD $80.00', 'Designer Wardrobe', 'Seller: Sophie P.', null),
  ('seed_30', 'Voyage Shorts', 'Caitlin Crisp', '6, 8, 10', 'Shorts', 'NZD $180.00', 'Designer Wardrobe', 'Seller: Jessie M.', null),
  ('seed_31', 'Chuck Taylor All Star Classic', 'Converse', '8', 'Shoes', 'NZD $60.00', 'Designer Wardrobe', 'Seller: Emba W. Photo did not load on site.', null),
  ('seed_32', 'Drawstring Dress', 'Orseund Iris', '10, 8', 'Dresses', 'NZD $420.00', 'Designer Wardrobe', 'Seller: Caitrin M. Photo did not load on site.', 'wardrobe-photos/orseund-iris-drawstring-dress-black-nobg.png'),
  ('seed_33', 'High Rise Stove Pipe Straight Leg', 'RE/DONE', '28', 'Jeans', 'NZD $165.82', 'Designer Wardrobe', 'Seller: Rebecca S. Photo did not load on site.', 'wardrobe-photos/redone-high-rise-stove-pipe-jean.jpg'),
  ('seed_34', 'Cotton Oversized White Shirt', 'Laing Home', '10, 8', 'Shirts', 'NZD $50.00', 'Designer Wardrobe', 'Seller: Andrea C.', 'wardrobe-photos/laing-home-cotton-oversized-white-shirt-nobg.png'),
  ('seed_35', 'Vada Jumper - Doe', 'Marle', '8', 'Knitwear', 'NZD $150.00', 'Designer Wardrobe', 'Seller: Evie P. Photo did not load on site.', 'wardrobe-photos/marle-vada-jumper-doe-v2-nobg.png'),
  ('seed_36', 'Backpack', 'Kate Spade', '-', 'Accessories', 'NZD $144.00', 'Designer Wardrobe', 'Seller: M A.', null),
  ('seed_37', 'Ribcage Straight Ankle - Black', 'Levi''s', '26', 'Jeans', 'NZD $85.00', 'Designer Wardrobe', 'Seller: Laura S.', 'wardrobe-photos/levis-ribcage-straight-ankle-black-nobg.png'),
  ('seed_38', 'Iren Knit - Grey', 'Assembly Label', '8, 10', 'Knitwear', 'NZD $70.00', 'Designer Wardrobe', 'Seller: Sryne W. Photo did not load on site.', 'wardrobe-photos/assembly-label-iren-knit-grey-v2-nobg.png'),
  ('seed_39', 'Tank', 'RE/DONE', '8', 'Tops', 'NZD $50.00', 'Designer Wardrobe', 'Seller: Lucy C. Photo did not load on site.', null),
  ('seed_40', 'So Shady (Ivory) sun hat', 'Sophie Store', 'S/M', 'Accessories', 'NZD $25.00', 'Designer Wardrobe', 'Seller: Elizabeth.', null),
  ('seed_41', 'Drop Shoulder Reversible Blouse', 'Orseund Iris', '8', 'Tops', 'NZD $293.00', 'Designer Wardrobe', 'Seller: Looks To Steal.', null),
  ('seed_42', 'Long sleeve', 'Commoners', '8', 'Tops', 'NZD $35.00', 'Designer Wardrobe', 'Seller: Darcy H. Photo sourced generically — tag in reference image reads a different brand, verify match.', 'wardrobe-photos/commoners-long-sleeve-white-nobg.png'),
  ('seed_43', 'Eloise Top', 'Marle', '6, 8', 'Tops', 'NZD $110.00', 'Designer Wardrobe', 'Seller: Mona H.', null),
  ('seed_44', 'High waist straight leg jeans', 'Levi''s', '24, 25, 26', 'Jeans', 'NZD $65.00', 'Designer Wardrobe', 'Seller: Bella B.', null),
  ('seed_45', 'Cara Mini Dress', 'Sir The Label', '8, 10', 'Dresses', 'NZD $120.00', 'Designer Wardrobe', 'Seller: Jade L.', null),
  ('seed_46', 'Alfalfa Shirt Indigo', 'Marle', '-', 'Jackets', '', '', '', 'wardrobe-photos/marle-alfalfa-shirt-indigo-nobg.png'),
  ('seed_47', 'Dallas Boots', 'City Beach Australia', '-', 'Shoes', 'NZD $89.99', '', 'Colour not specified — used Black variant.', 'wardrobe-photos/city-beach-dallas-boots-black.jpg'),
  ('seed_48', 'Ana Long Sleeve Top Green', 'Marle', '-', 'Tops', 'NZD $182.00', '', 'Used ''Tapenade'' colourway (closest olive/green match found).', 'wardrobe-photos/marle-ana-top-green-tapenade-nobg.png'),
  ('seed_49', 'Rib Knit Polo Top', 'St. Agni', '-', 'Tops', 'NZD $259.00', '', 'Sourced as ''Petit Polo Knit Top'' on St. Agni''s own site — verify same item.', 'wardrobe-photos/st-agni-rib-knit-polo-top-black.jpg'),
  ('seed_50', 'Paris Dress', 'St. Agni', '-', 'Dresses', 'NZD $429.00', '', '', 'wardrobe-photos/st-agni-paris-dress-flat-nobg.png'),
  ('seed_51', 'Marina Seersucker Tee', 'AFENDS', '-', 'Tops', '', '', 'Womens Marina - Seersucker Top - Marina.', 'wardrobe-photos/afends-marina-seersucker-top-flat-nobg.png'),
  ('seed_52', 'Crew Neck Sweater', 'SIR the Label', '-', 'Knitwear', 'NZD $403.47', '', '', 'wardrobe-photos/sir-the-label-crew-neck-sweater-black-nobg.png'),
  ('seed_53', 'Milano High Waist Pants', 'St. Agni', '-', 'Pants', '', '', 'Colour not specified — used Black variant.', 'wardrobe-photos/st-agni-milano-high-waist-pants-black-flat-nobg.png'),
  ('seed_54', 'Long Sleeve Knit', 'Country Road', '-', 'Tops', 'NZD $120.00', 'Infinite Definite', 'Black. Generic name — used Merino Wool Silk Long Sleeve Knit as best guess, verify style.', 'wardrobe-photos/country-road-long-sleeve-knit-black-nobg.png'),
  ('seed_55', 'Neva Beanie', 'Remain', '-', 'Accessories', 'NZD $75.65', '', '', null),
  ('seed_56', 'Marle Maxi Dress Ivy Black', 'Marle', '-', 'Dresses', 'NZD $229.00', '', '', 'wardrobe-photos/marle-maxi-dress-ivy-black-flat-nobg.png'),
  ('seed_57', 'Cleo boot', 'Bronwyn Footwear', '-', 'Shoes', 'NZD $136.00', '', '', 'wardrobe-photos/bronwyn-footwear-cleo-boot-nobg.png'),
  ('seed_58', 'Layla Flares Carob', 'Indigo Luna', '-', 'Pants', '', '', '', 'wardrobe-photos/indigo-luna-layla-flares-carob-nobg.png'),
  ('seed_59', 'Agni Flares Chocolate', 'Indigo Luna', '-', 'Pants', '', '', 'Requested as ''Agnis Flares brown'' — closest match is the Chocolate colourway.', 'wardrobe-photos/indigo-luna-agni-flares-chocolate-nobg.png'),
  ('seed_60', 'Uma Dress', 'Marle', '-', 'Dresses', '', '', '', 'wardrobe-photos/marle-uma-dress-nobg.png'),
  ('seed_61', 'Lola Barrel Pant', 'Assembly Label', '-', 'Pants', '', '', 'Dark Military Green.', 'wardrobe-photos/assembly-label-lola-barrel-pant-dark-military-green-nobg.png'),
  ('seed_62', 'Groove Flare Yoga Tights', 'Lululemon', '-', 'Pants', '', '', 'Black.', 'wardrobe-photos/lululemon-groove-flare-yoga-tights-black-nobg.png'),
  ('seed_63', 'Cargo Pant', '', '-', 'Pants', '', '', 'Olive/sage colour.', 'wardrobe-photos/cargo-pant-olive-nobg.png'),
  ('seed_64', 'Long Sleeve Black', 'ME+EM', '-', 'Tops', '', '', '', 'wardrobe-photos/long-sleeve-black-meem-nobg.png'),
  ('seed_65', 'Pink Tee', '', '-', 'Tops', '', '', '', 'wardrobe-photos/pink-tee-nobg.png'),
  ('seed_66', 'Black Tee', '', '-', 'Tops', '', '', '', 'wardrobe-photos/black-tee-nobg.png'),
  ('seed_67', 'White Tee', '', '-', 'Tops', '', '', '', 'wardrobe-photos/white-tee-nobg.png'),
  ('seed_68', 'Bucket Hat Beige', 'Lack of Colour', '-', 'Accessories', '', '', '', 'wardrobe-photos/lack-of-colour-bucket-hat-beige-nobg.png'),
  ('seed_69', 'Straw Bucket Hat', '', '-', 'Accessories', '', '', '', 'wardrobe-photos/straw-bucket-hat-nobg.png'),
  ('seed_70', 'Black Bucket Hat', '', '-', 'Accessories', '', '', '', 'wardrobe-photos/black-bucket-hat-nobg.png'),
  ('seed_71', 'Boston Clogs', 'Birkenstock', '-', 'Shoes', '', '', '', 'wardrobe-photos/birkenstock-boston-nobg.png'),
  ('seed_72', 'Turtleneck Jumper', 'Arket', '-', 'Knitwear', '', '', '', 'wardrobe-photos/arket-turtleneck-jumper-nobg.png'),
  ('seed_73', 'Overalls', 'Calvin Klein', '-', 'Pants', '', '', 'Denim dungarees/overalls.', 'wardrobe-photos/ck-overalls-nobg.png'),
  ('seed_74', 'Cream Denim Shirt', 'Marle', '-', 'Jackets', '', '', '', 'wardrobe-photos/marle-cream-denim-shirt-nobg.png'),
  ('seed_75', 'Brown Baby Tee', 'Cotton On', '-', 'Tops', '', '', 'Brown/tan stripe.', 'wardrobe-photos/cotton-on-brown-baby-tee-nobg.png'),
  ('seed_76', 'Denim Jacket', 'Levi''s', '-', 'Jackets', '', '', 'Corduroy collar.', 'wardrobe-photos/levis-denim-jacket-corduroy-collar-nobg.png'),
  ('seed_77', 'Quilted Jacket', '', '-', 'Jackets', '', '', 'Navy.', 'wardrobe-photos/quilted-jacket-navy-nobg.png'),
  ('seed_78', 'White Jeans', 'AGOLDE', '-', 'Jeans', '', '', '', 'wardrobe-photos/agolde-white-jeans-nobg.png'),
  ('seed_79', 'Red Tee', '', '-', 'Tops', '', '', '', 'wardrobe-photos/red-tee-nobg.png')
on conflict (id) do nothing;
